version: '2'

volumes:
  ibanmanager_postgres_data_dev: {}
  ibanmanager_postgres_backup_dev: {}

services:
  ibanmanager_postgres:
    build: ./compose/postgres
    volumes:
      - ibanmanager_postgres_data_dev:/var/lib/postgresql/data
      - ibanmanager_postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=ibanmanager
    #We expose the port to the host so we can connect directly to the DB (wo linking to it from another container)
    ports:
      - "5432:5432"

  ibanmanager_django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file: .env
    depends_on:
      - ibanmanager_postgres
    environment:
      - POSTGRES_USER=ibanmanager
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - ibanmanager_postgres