FROM python:3.6

ENV PYTHONUNBUFFERED 1

ENV ROOTDIR /usr/local/

WORKDIR $ROOTDIR/

ADD ./compose/django/compile.sh $ROOTDIR/src/
ADD ./compose/django/install_extras.sh $ROOTDIR/src/


# Compilation
RUN chmod 777 src/install_extras.sh
RUN src/install_extras.sh

RUN chmod 777 src/compile.sh
RUN src/compile.sh

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

RUN groupadd -r ibanmanager && useradd -r -g ibanmanager ibanmanager
COPY . /app
RUN chown -R ibanmanager /app

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
