# Generated by Django 2.1.1 on 2018-09-19 13:47

from django.db import migrations, models
import stdnum.iban
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('iban', models.CharField(max_length=45, validators=[stdnum.iban.validate])),
            ],
            options={
                'ordering': ('-modified_at',),
                'abstract': False,
            },
        ),
    ]
